name: typora-alanzanattadev # you probably want to 'snapcraft register <name>'
version: '0.9.44' # just for humans, typically '1.2+git' or '1.3.2'
summary: Easy to use markdown editor # 79 char long summary
description: |
  Typora will give you a seamless experience as both a reader and a writer.
  It removes the preview window, mode switcher, syntax symbols of markdown source code,
  and all other unnecessary distractions. Replace them with a real live preview feature
  to help you concentrate the content itself.

grade: stable # must be 'stable' to release into candidate/stable channels
confinement: classic # use 'strict' once you have the right plugs and slots

parts:
  typora:
    # See 'snapcraft plugins'
    plugin: dump
    source: https://typora.io/linux/typora_0.9.44_amd64.deb
    source-type: deb
    prepare: |
      sed -i 's|Icon=typora|Icon=/snap/typora-alanzanattadev/current/usr/share/icons/hicolor/256x256/apps/typora\.png|g' usr/share/applications/typora.desktop
    stage-packages:
      # Required packages
      - libgconf-2-4
      - libpng16-16
      - zlib1g
      - libc6
      # GTK modules
      - libcanberra-gtk3-0
      - libcanberra-gtk3-module
      - libgail-3-0
      - libatk-bridge2.0-0
      # default packages
      - libappindicator1
      - libasound2
      - libcurl3-gnutls
      - libgtk2.0-0
      - libnotify4
      - libnspr4
      - libnss3
      - libpcre3
      - libpulse0
      - libxss1
      - libxtst6
    after:
      - desktop-glib-only
apps:
  typora-alanzanattadev:
    command: usr/bin/typora
    desktop: usr/share/applications/typora.desktop
    plugs:
      - home
      - x11
      - unity7
      - browser-support
      - network
      - gsettings
      - pulseaudio
      - opengl
      - desktop
      - wayland
